# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import polymetis_pb2 as polymetis__pb2


class PolymetisControllerServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetController = channel.stream_unary(
                '/PolymetisControllerServer/SetController',
                request_serializer=polymetis__pb2.ControllerChunk.SerializeToString,
                response_deserializer=polymetis__pb2.LogInterval.FromString,
                )
        self.UpdateController = channel.stream_unary(
                '/PolymetisControllerServer/UpdateController',
                request_serializer=polymetis__pb2.ControllerChunk.SerializeToString,
                response_deserializer=polymetis__pb2.LogInterval.FromString,
                )
        self.TerminateController = channel.unary_unary(
                '/PolymetisControllerServer/TerminateController',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.LogInterval.FromString,
                )
        self.GetRobotState = channel.unary_unary(
                '/PolymetisControllerServer/GetRobotState',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.RobotState.FromString,
                )
        self.GetRobotStateStream = channel.unary_stream(
                '/PolymetisControllerServer/GetRobotStateStream',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.RobotState.FromString,
                )
        self.GetRobotStateLog = channel.unary_stream(
                '/PolymetisControllerServer/GetRobotStateLog',
                request_serializer=polymetis__pb2.LogInterval.SerializeToString,
                response_deserializer=polymetis__pb2.RobotState.FromString,
                )
        self.GetEpisodeInterval = channel.unary_unary(
                '/PolymetisControllerServer/GetEpisodeInterval',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.LogInterval.FromString,
                )
        self.InitRobotClient = channel.unary_unary(
                '/PolymetisControllerServer/InitRobotClient',
                request_serializer=polymetis__pb2.RobotClientMetadata.SerializeToString,
                response_deserializer=polymetis__pb2.Empty.FromString,
                )
        self.ControlUpdate = channel.unary_unary(
                '/PolymetisControllerServer/ControlUpdate',
                request_serializer=polymetis__pb2.RobotState.SerializeToString,
                response_deserializer=polymetis__pb2.TorqueCommand.FromString,
                )
        self.GetRobotClientMetadata = channel.unary_unary(
                '/PolymetisControllerServer/GetRobotClientMetadata',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.RobotClientMetadata.FromString,
                )


class PolymetisControllerServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetController(self, request_iterator, context):
        """
        **** User client methods *****

        These are user-facing methods allowing you to change
        the current controller and get the full robot states.

        Switch the current controller, and return the log index at start of 
        controller execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateController(self, request_iterator, context):
        """Update the current controller, and return the log index at the point
        where update takes effect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateController(self, request, context):
        """Terminate the current controller, and return the log indices at
        start & end of controller execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotState(self, request, context):
        """Get the current robot state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotStateStream(self, request, context):
        """Get a stream of robot states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotStateLog(self, request, context):
        """Get a stream of past robot states
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpisodeInterval(self, request, context):
        """Get the start & end log indices of current controller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitRobotClient(self, request, context):
        """
        **** Robot client methods *****

        Clients implementing these methods should provide the robot
        environment, e.g. the process which connects to the robot
        hardware or simulation.

        Send relevant metadata to initialize RobotClient connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlUpdate(self, request, context):
        """Compute torque command in response to a robot state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotClientMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolymetisControllerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetController': grpc.stream_unary_rpc_method_handler(
                    servicer.SetController,
                    request_deserializer=polymetis__pb2.ControllerChunk.FromString,
                    response_serializer=polymetis__pb2.LogInterval.SerializeToString,
            ),
            'UpdateController': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateController,
                    request_deserializer=polymetis__pb2.ControllerChunk.FromString,
                    response_serializer=polymetis__pb2.LogInterval.SerializeToString,
            ),
            'TerminateController': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateController,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.LogInterval.SerializeToString,
            ),
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.RobotState.SerializeToString,
            ),
            'GetRobotStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRobotStateStream,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.RobotState.SerializeToString,
            ),
            'GetRobotStateLog': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRobotStateLog,
                    request_deserializer=polymetis__pb2.LogInterval.FromString,
                    response_serializer=polymetis__pb2.RobotState.SerializeToString,
            ),
            'GetEpisodeInterval': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpisodeInterval,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.LogInterval.SerializeToString,
            ),
            'InitRobotClient': grpc.unary_unary_rpc_method_handler(
                    servicer.InitRobotClient,
                    request_deserializer=polymetis__pb2.RobotClientMetadata.FromString,
                    response_serializer=polymetis__pb2.Empty.SerializeToString,
            ),
            'ControlUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlUpdate,
                    request_deserializer=polymetis__pb2.RobotState.FromString,
                    response_serializer=polymetis__pb2.TorqueCommand.SerializeToString,
            ),
            'GetRobotClientMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotClientMetadata,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.RobotClientMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PolymetisControllerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PolymetisControllerServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetController(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/PolymetisControllerServer/SetController',
            polymetis__pb2.ControllerChunk.SerializeToString,
            polymetis__pb2.LogInterval.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateController(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/PolymetisControllerServer/UpdateController',
            polymetis__pb2.ControllerChunk.SerializeToString,
            polymetis__pb2.LogInterval.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PolymetisControllerServer/TerminateController',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.LogInterval.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PolymetisControllerServer/GetRobotState',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.RobotState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PolymetisControllerServer/GetRobotStateStream',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.RobotState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotStateLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PolymetisControllerServer/GetRobotStateLog',
            polymetis__pb2.LogInterval.SerializeToString,
            polymetis__pb2.RobotState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEpisodeInterval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PolymetisControllerServer/GetEpisodeInterval',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.LogInterval.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitRobotClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PolymetisControllerServer/InitRobotClient',
            polymetis__pb2.RobotClientMetadata.SerializeToString,
            polymetis__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PolymetisControllerServer/ControlUpdate',
            polymetis__pb2.RobotState.SerializeToString,
            polymetis__pb2.TorqueCommand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotClientMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PolymetisControllerServer/GetRobotClientMetadata',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.RobotClientMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GripperServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitRobotClient = channel.unary_unary(
                '/GripperServer/InitRobotClient',
                request_serializer=polymetis__pb2.GripperMetadata.SerializeToString,
                response_deserializer=polymetis__pb2.Empty.FromString,
                )
        self.GetRobotClientMetadata = channel.unary_unary(
                '/GripperServer/GetRobotClientMetadata',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.GripperMetadata.FromString,
                )
        self.GetState = channel.unary_unary(
                '/GripperServer/GetState',
                request_serializer=polymetis__pb2.Empty.SerializeToString,
                response_deserializer=polymetis__pb2.GripperState.FromString,
                )
        self.Goto = channel.unary_unary(
                '/GripperServer/Goto',
                request_serializer=polymetis__pb2.GripperCommand.SerializeToString,
                response_deserializer=polymetis__pb2.Empty.FromString,
                )
        self.ControlUpdate = channel.unary_unary(
                '/GripperServer/ControlUpdate',
                request_serializer=polymetis__pb2.GripperState.SerializeToString,
                response_deserializer=polymetis__pb2.GripperCommand.FromString,
                )


class GripperServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitRobotClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotClientMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Goto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GripperServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitRobotClient': grpc.unary_unary_rpc_method_handler(
                    servicer.InitRobotClient,
                    request_deserializer=polymetis__pb2.GripperMetadata.FromString,
                    response_serializer=polymetis__pb2.Empty.SerializeToString,
            ),
            'GetRobotClientMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotClientMetadata,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.GripperMetadata.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=polymetis__pb2.Empty.FromString,
                    response_serializer=polymetis__pb2.GripperState.SerializeToString,
            ),
            'Goto': grpc.unary_unary_rpc_method_handler(
                    servicer.Goto,
                    request_deserializer=polymetis__pb2.GripperCommand.FromString,
                    response_serializer=polymetis__pb2.Empty.SerializeToString,
            ),
            'ControlUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlUpdate,
                    request_deserializer=polymetis__pb2.GripperState.FromString,
                    response_serializer=polymetis__pb2.GripperCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GripperServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GripperServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitRobotClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GripperServer/InitRobotClient',
            polymetis__pb2.GripperMetadata.SerializeToString,
            polymetis__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotClientMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GripperServer/GetRobotClientMetadata',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.GripperMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GripperServer/GetState',
            polymetis__pb2.Empty.SerializeToString,
            polymetis__pb2.GripperState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Goto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GripperServer/Goto',
            polymetis__pb2.GripperCommand.SerializeToString,
            polymetis__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GripperServer/ControlUpdate',
            polymetis__pb2.GripperState.SerializeToString,
            polymetis__pb2.GripperCommand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
